// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NsbmLesson12.Data;

#nullable disable

namespace NsbmLesson12.Migrations
{
    [DbContext(typeof(NsbmAppDbContext))]
    partial class NsbmAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NsbmLesson12.Models.NsbmCategory", b =>
                {
                    b.Property<int>("NsbmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NsbmId"));

                    b.Property<DateTime>("NsbmCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nsbmname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NsbmId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("NsbmLesson12.Models.NsbmProduct", b =>
                {
                    b.Property<int>("NsbmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NsbmId"));

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("NsbmCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NsbmCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NsbmImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NsbmName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("NsbmPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("NsbmStatus")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("NsbmsalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NsbmId");

                    b.HasIndex("NsbmCategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("NsbmLesson12.Models.NsbmProduct", b =>
                {
                    b.HasOne("NsbmLesson12.Models.NsbmCategory", "NsbmCategory")
                        .WithMany("NsbmProducts")
                        .HasForeignKey("NsbmCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NsbmCategory");
                });

            modelBuilder.Entity("NsbmLesson12.Models.NsbmCategory", b =>
                {
                    b.Navigation("NsbmProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
